name: on-baording-CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install/Lint/Test server dependencies
        run: |
          cd server
          npm install --no-optional
          npm audit fix
          
      - name: Install client dependencies
        run: |
          cd client
          npm install --no-optional
          npm audit fix
